#!/bin/bash

echo
echo -e "\e[1m\e[32mUpdating Packages\e[39m"
echo
apt update -y &&
apt upgrade -y &&
apt full-upgrade -y &&
apt autoremove -y
apt clean

echo
pushd /opt >/dev/null

for dir in `find . -type d`
do
	if [ -d "$dir/.git" ]; then
		echo -e "\e[1m\e[32mUpdating $dir\e[39m"
		pushd "$dir" > /dev/null && git pull
		if [ -f "update.sh" ]; then
	                ./update.sh
	        fi
		if [ -f "requirements.txt" ]; then
			pip install -r requirements.txt
		fi
		if [ -f "setup.py" ]; then
			python setup.py install
		fi
		if [ -f "setup/install.sh" ]; then
			./setup/install.sh
		fi
		popd >/dev/null
		echo
	fi
done

popd >/dev/null

echo
echo -e "\e[1m\e[32mUpdating locate DB\e[39m"
echo 
updatedb

echo
echo -e "\e[1m\e[32mDone!\e[39m"

