#!/bin/bash

echo
echo -e "\e[1m\e[32mUpdating Kali\e[0m"
echo
apt-get update -y &&
apt-get upgrade -y &&
apt-get full-upgrade -y &&
apt-get autoremove -y

echo
pushd /opt >/dev/null

for dir in `find . -type d`
do
	if [ -d "$dir/.git" ]; then
		echo -e "\e[1m\e[32mUpdating $dir\e[0m"
		pushd "$dir" > /dev/null && git pull
		if [ -f "update.sh" ]; then
	                ./update.sh
	        fi
		popd >/dev/null
		echo
	fi
done

popd >/dev/null
